name: DockerCompose

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_COINMARKETCAP_APIKEY: ${{ secrets.COINMARKETCAP_APIKEY }}
          envkey_MY_BOT_SECRET_TOKEN: ${{ secrets.MY_BOT_SECRET_TOKEN }}
          envkey_PYTHONUNBUFFERED: 1
          file_name: .env
          fail_on_empty: true
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.6 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
