name: DockerCompose

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_COINMARKETCAP_APIKEY: ${{ secrets.COINMARKETCAP_APIKEY }}
          envkey_MY_BOT_SECRET_TOKEN: ${{ secrets.MY_BOT_SECRET_TOKEN }}
          envkey_PYTHONUNBUFFERED: 1 
          file_name: secrets.env
          fail_on_empty: true        
      
      - name: Print the final result
        shell: bash
        run: |
          ls -a
          value=`cat secrets.env`
          echo The result is $value
       
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "./secrets.env"
          target: "/home/ubuntu/secrets.env"
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.6 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            c
